services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: spring-postgres175
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
      POSTGRES_DB: demo
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      postgres-network:
        ipv4_address: 172.20.0.2
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 53cret
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    networks:
      postgres-network:
        ipv4_address: 172.20.0.3
networks:
  postgres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16